django/totmann/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views

urlpatterns = [
    # Examples:
    # url(r'^$', 'totmann.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^$', auth_views.login, name='home'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^check/', include('core.urls', namespace='core')),
    url(r'^web/', include('web.urls', namespace='web')),
    url(r'^accounts/', include('registration.backends.default.urls')),
    url('^', include('django.contrib.auth.urls'))
]

django/web/urls.py
from django.conf.urls import include, url
from . import views

urlpatterns = [
    url(r'^list$', views.list, name='list'),
    url(r'^list/(?P<tag_selected>.+)', views.list, name='list_filter_by_tag'),
    url(r'^timeline$', views.timeline, name='timeline'),
    url(r'^details/(?P<apikey>[a-zA-Z0-9-_]+)', views.details, name='details'),
    url(r'^toggle', views.toggle, name='toggle'),
    url(r'^add', views.check_add, name='check-add'),
    url(r'^notification-add', views.notification_add, name='notification-add'),
    url(r'^confirm/(?P<token>[a-fA-F0-9]+)', views.confirm_email, name='confirm-email'),
    url(r'^notification-remove', views.notification_remove, name='notification-remove'),
    #                       url(r'^([a-zA-Z0-9-_]+)/finished', views.event_finished, name='rest-event-finished'),
    #                       url(r'^([a-zA-Z0-9-_]+)/log', views.event_log, name='rest-event-log'),
]

django/web/templates/web/details.html
{% extends 'base.html' %}
{% load absurl %}

{% block title %}View/edit check{% endblock %}
{% block extralinks %}<a href="{% url "web:list" %}">home</a> <a href="#events">event log</a> <a href="#reporting">reporting URLs</a>{% endblock %}
{% block content %}
<script>
function check_remove() {
    return confirm("Do you want to delete this check?");
}
function change_reporting_urls(sel) {
    show_hide_class("plain", sel == "plain");
    show_hide_class("wget", sel == "wget");
    show_hide_class("curl", sel == "curl");
}
function show_hide_class(cls, show) {
    var elements = document.querySelectorAll("." + cls);
    var i;
    for (i = 0; i < elements.length; i++) {
	elements[i].style.display = show ? "initial" : "none";
    }
}

</script>

{{ form.errors }}
<form action="{% url 'web:details' check.apikey %}#settings" method="post">
  {% csrf_token %}
  <div class="row">
    </div>
  <div id="settings" class="row">
    {{ form.name.label_tag }}
    {% if form.name.help_text %}
    <div class="help">{{ form.name.help_text }}</div>
    {% endif %}
    {{ form.prefix }}/{{ form.name }}
    {{ form.prefix.errors }}
    {{ form.name.errors }}
  </div>
  <div class="row">
    {{ form.tags.label_tag }}
    {% if form.tags.help_text %}
    <div class="help">{{ form.tags.help_text }}</div>
    {% endif %}
    {{ form.tags }}
    {{ form.tags.errors }}
  </div>
  <div class="row">
    {{ form.interval.label_tag }}
    {% if form.interval.help_text %}
    <div class="help">{{ form.interval.help_text }}</div>
    {% endif %}
    {{ form.interval }}
    {{ form.interval.errors }}
  </div>
  <div class="row">
    {{ form.expected_regex.label_tag }}
    {% if form.expected_regex.help_text %}
    <div class="help">{{ form.expected_regex.help_text }}</div>
    {% endif %}
    <input type="text" name="{{ form.expected_regex.html_name }}" name="{{ form.expected_regex.id_for_label }}" value="{{ form.expected_regex.value }}" class="u-full-width">
    {{ form.expected_regex.errors }}
  </div>
  <div class="row">
    {{ form.alert_regex.label_tag }}
    {% if form.alert_regex.help_text %}
    <div class="help">{{ form.alert_regex.help_text }}</div>
    {% endif %}
    <input type="text" name="{{ form.alert_regex.html_name }}" name="{{ form.alert_regex.id_for_label }}" value="{{ form.alert_regex.value }}" class="u-full-width">
    {{ form.alert_regex.errors }}
  </div>
  <div class="row">
    {{ form.allowed_return_codes.label_tag }}
    {% if form.allowed_return_codes.help_text %}
    <div class="help">{{ form.allowed_return_codes.help_text }}</div>
    {% endif %}
    {{ form.allowed_return_codes }}
    {{ form.allowed_return_codes.errors }}
  </div>
  <div class="row">
    {{ form.store_events.label_tag }}
    {% if form.store_events.help_text %}
    <div class="help">{{ form.store_events.help_text }}</div>
    {% endif %}
    {{ form.store_events }}
    {{ form.store_events.errors }}
  </div>
  <div class="row">
    {{ form.notifications.label_tag }}
    {% if form.notifications.help_text %}
    <div class="help">{{ form.notifications.help_text }}</div>
    {% endif %}
    {% for radio in form.notifications %}
    <label for="{{ radio.id_for_label }}">
      <span class="radio">{{ radio.tag }}</span>
      <span class="label-body">{{ radio.choice_label }}</span>
    </label>
    {% endfor %}
    {{ form.notifications.errors }}
  </div>
  <button type="submit" class="button-primary" name="action" value="save">Save changes</button>   <button type="submit" name="action" value="remove" onclick="return check_remove();">Remove check</button></form>
<h4 id="events">Event log</h4>
{% if check.is_late %}
<p>
  <i class="fa fa-warning orange"></i> This job is running late!
</p>
{% endif %}
<p>{{ events.paginator.count }} events recorded</p>
<form>
  <table class="u-full-width" id="events">
    <thead>
      <tr>
	<th style="width: 1em;"></th>
	<th>Type</th>
	<th>Date/Time</th>
	<th>Output/Return Code</th>
      </tr>
    </thead>
    <tbody>
      {% if events.has_previous %}
      <tr>
	<td colspan="4" style="text-align: center">
          showing page {{ events.number }} of {{events.paginator.num_pages }} &middot; <a href="?page={{ events.previous_page_number }}#events">previous</a>
	</td>
      </tr>
w      {% endif %}
      {% for e in events %}
      <tr id="event-{{ e.id }}">
	<td><i class="fa fa-stop status-{{ e.get_unified_status }}" title="{{ e.get_verbose_description }}"></i></td>
	<td>{{ e.event }}</td>
	<td>{{ e.timestamp }}</td>
	<td style="width:60%">{% if e.event == 'finished' %}return code: {{ e.content }}{% elif e.event == 'log' %}<textarea  style="width:100%; height:100px;">{{ e.content }}</textarea>{% endif %}</td>
      </tr>
      {% endfor %}
      {% if events.has_next %}
      <tr>
	<td colspan="4" style="text-align: center">
          showing page {{ events.number }} of {{events.paginator.num_pages }} &middot; <a href="?page={{ events.next_page_number }}#events">next</a>
	</td>
      </tr>
      {% endif %}
    </tbody>
  </table>
</form>

<h5 id="reporting">Reporting URLs</h5>
<p>All URLs must be called via POST requests.</p>
<p>
  <label for="show-urls">Show URLs: </label>
  <select id="show-urls" onchange="change_reporting_urls(this.value);">
    <option value="plain">plain</option>
    <option value="curl">for curl</option>
    <option value="wget">for wget</option>
  </select>
</p>
<p>

  <div class="plain">
    <label>To notify totmann of the start time of a job run:</label>
    <span>Send a POST request to <span class="url">{% absurl 'core:event-start' check.apikey %}</span></span>
    <label>To log a successful run (or an error code for an unsuccessful run):</label>
    <span>Send a POST request to <span class="url">{% absurl 'core:event-finished' check.apikey %}</span> . The request may contain the numeric return code of the command in the body of the request (without any further encapsulation).</span>
    <label>To send the output of a command to totmann:</label>
    <span>Send a POST request containing the log file (without any further encapsulation or encoding) to <span class="url">{% absurl 'core:event-log' check.apikey %}</span></span>
  </div>

  
  <div class="wget">
    <label>To notify totmann of the start time of a job run:</label>
    <span class="url">wget --post-data='' -O/dev/null --quiet {% absurl 'core:event-start' check.apikey %}</span>
    <label>To log a successful run (or an error code for an unsuccessful run):</label>
    <span class="url">wget --post-data="$?" -O/dev/null --quiet {% absurl 'core:event-finished' check.apikey %}</span>
    <label>To send the output of a command to totmann:</label>
    <span class="url">wget --post-file=/tmp/logfile -O/dev/null --quiet {% absurl 'core:event-log' check.apikey %}</span>
    <label>Wrapper script using wget:</label>
    <p>Usage: <span class="url">./totmann-wrapper.sh {{ check.apikey }} command arg1 arg2...</span></p>
    <pre class="url">
#!/bin/bash
if [ "$#" -lt 3 ]
then
    exit "Usage: $0 apikey command"
fi
APIKEY="$1"
shift
COMMAND="$@"
wget --post-data='' -O/dev/null --quiet {% absurl 'core:event-start' '$APIKEY' %}
"$@" > /tmp/totmann-output 2>&1
wget --post-data="$?" -O/dev/null --quiet {% absurl 'core:event-finished' '$APIKEY' %}
wget --post-file=/tmp/totmann-output -O/dev/null --quiet {% absurl 'core:event-log' '$APIKEY' %} && rm /tmp/totmann-output
</pre>
</div>


<div class="curl">
  <label>To notify totmann of the start time of a job run:</label>
  <span class="url">curl -fsS -o /dev/null --data-binary '' {% absurl 'core:event-start' check.apikey %}</span>
  <label>To log a successful run (or an error code for an unsuccessful run):</label>
  <span class="url">curl -fsS -o /dev/null --data-binary "$?" {% absurl 'core:event-finished' check.apikey %}</span>
  <label>To send the output of a command to totmann:</label>
  <span class="url">curl -fsS -o /dev/null --data-binary @/tmp/logfile {% absurl 'core:event-log' check.apikey %}</span>
  <label>Wrapper script using curl:</label>
  <p>Usage: <span class="url">./totmann-wrapper.sh {{ check.apikey }} command arg1 arg2...</span></p>
  <pre class="url">
#!/bin/bash
if [ "$#" -lt 3 ]
then
    exit "Usage: $0 apikey command"
fi
APIKEY="$1"
shift
COMMAND="$@"
curl -fsS -o /dev/null --data-binary '' {% absurl 'core:event-start' '$APIKEY' %}
"$@" > /tmp/totmann-output 2>&1
curl -fsS -o /dev/null --data-binary "$?" {% absurl 'core:event-finished' '$APIKEY' %}
curl -fsS -o /dev/null --data-binary @/tmp/totmann-output {% absurl 'core:event-log' '$APIKEY' %}</pre>
</div>
  <script>
    change_reporting_urls('plain');
  </script>
</p>

{% endblock %}

django/web/templates/web/index.html
<!DOCTYPE html>
<html lang="en">
<head>

  <!-- Basic Page Needs
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <meta charset="utf-8">
  <title>Your page title here :)</title>
  <meta name="description" content="">
  <meta name="author" content="">

  <!-- Mobile Specific Metas
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- FONT
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <link href="//fonts.googleapis.com/css?family=Raleway:400,300,600" rel="stylesheet" type="text/css">

  <!-- CSS
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <link rel="stylesheet" href="css/normalize.css">
  <link rel="stylesheet" href="css/skeleton.css">

  <!-- Favicon
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <link rel="icon" type="image/png" href="images/favicon.png">

</head>
<body>

  <!-- Primary Page Layout
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <div class="container">
    <div class="row">
      <div class="one-half column" style="margin-top: 25%">
        <h4>Basic Page</h4>
        <p>This index.html page is a placeholder with the CSS, font and favicon. It's just waiting for you to add some content! If you need some help hit up the <a href="http://www.getskeleton.com">Skeleton documentation</a>.</p>
      </div>
    </div>
  </div>

<!-- End Document
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
</body>
</html>

django/web/templates/web/list.html
{% extends 'base.html' %}
{% block title %}Your Checks{% if tag_selected %} with tag <a href="{% url 'web:list_filter_by_tag' tag_selected %}" class="check-tag active">{{ tag_selected }}</a> 
<small>(<a href="{% url 'web:list' %}">remove filter</a>)</small>{% endif %}{% endblock %}

{% block content %}
{% for tag in tags %}
<a href="{% url 'web:list_filter_by_tag' tag %}" class="check-tag {% if tag.name == tag_selected %}active{% endif %}">{{ tag }}</a>
{% endfor %}

<table class="u-full-width">
  <thead>
    <tr>
      <th style="width: 1em;"></th>
      <th>Name</th>
      <th>Last Success</th>
      <th>History</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    {% for check in checks_enabled %}
    
      <form action="{% url "web:toggle" %}" method="post">
      {% csrf_token %}
      <tr>
	<td>{% if check.is_late %}<i class="fa fa-warning orange" title="Job is running late!"></i>{% endif %} {% if check.notifications.count == 0 %}<i class="fa fa-warning orange" title="No notifications are enabled for this check!"></i>{% endif %}</td>
	<td><div>{% for tag in check.tags.all %}<a href="{% url 'web:list_filter_by_tag' tag %}" class="check-tag {% if tag.name == tag_selected %}active{% endif %}">{{ tag }}</a>{% endfor %}</div>{% if check.prefix %}{% ifchanged check.prefix %}<b>{% endifchanged %}{{ check.prefix }}{% ifchanged check.prefix %}</b>{% endifchanged %}/{% endif %}{{ check.name }}</td>
	<td>{{ check.last_success.timestamp }}</td>
	<td>{% for e in check.get_history %}<a href="{% url 'web:details' check.apikey %}#event-{{ e.id }}" title="{{ e.timestamp }}: {{ e.get_verbose_description }}"><i class="fa fa-stop status-{{ e.get_unified_status }}"></i></a>{% endfor %}</td>
	<td>
	  <a href="{% url "web:details" check.apikey %}#events">logs</a>
	  <a href="{% url 'web:details' check.apikey %}">details</a>
	  <button class="linkbutton" name="apikey" value="{{ check.apikey }}">disable</button></td>
      </tr>
      </form>
      {% endfor %}
      
    <form action="{% url "web:check-add" %}" method="post">
      {% csrf_token %}
      <tr>
	<td></td>
	<td colspan="3"><input type="text" name="name" pattern=".{1,}" required placeholder="new check" style="width: 60%"></td>
	<td><input type="submit" name="add" value="Add"></td>
      </tr>
    </form>
  </tbody>
</table>
<h5>Disabled Checks</h5>
<p>These checks are disabled and will not cause any notifications.</p>
<table class="u-full-width">
  <thead>
    <tr>
      <th>Name</th>
      <th>Last Action</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <form action="{% url "web:toggle" %}" method="post">
      {% csrf_token %}
      {% for check in checks_disabled %}
      <tr>
	<td><div>{% for tag in check.tags.all %}<a href="{% url 'web:list_filter_by_tag' tag %}" class="check-tag {% if tag.name == tag_selected %}active{% endif %}">{{ tag }}</a>{% endfor %}</div>{% if check.prefix %}{% ifchanged check.prefix %}<b>{% endifchanged %}{{ check.prefix }}{% ifchanged check.prefix %}</b>{% endifchanged %}/{% endif %}{{ check.name }}</td>
	<td>{{ check.last_action.timestamp }}</td>
	<td><button class="linkbutton" name="apikey" value="{{ check.apikey }}">enable</button></td>
      </tr>
      {% endfor %}
    </form>
  </tbody>
</table>

<h4>Your Notification Channels.</h4>
<p>Currently, only email notifications are supported. We
  suggest to use <a href="https://pushover.net/" target="_blank">pushover</a> to
  receive notifications on your smartphone.</p>

<table class="u-full-width">
  <thead>
    <tr>
      <th>E-Mail address</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <form action="{% url "web:notification-remove" %}" method="post">
      {% csrf_token %}
      {% for n in notifications %}
      <tr>
	<td>{{ n.address }}{% if not n.is_confirmed %} <i class="fa fa-warning gray" title="Please confirm email address! A message was sent to you, please click on link contained in that message."></i>{% endif %}</td>
	<td><button class="linkbutton" name="remove-notification" value="{{ n.id }}">remove</button></td>
      </tr>
      {% endfor %}
    </form>
    <form action="{% url "web:notification-add" %}" method="post">
      {% csrf_token %}
      <tr>
	<td><input type="email" name="email" placeholder="new address"></td>
	<td><input type="submit" name="add" value="Add"></td>
      </tr>
    </form>
  </tbody>
</table>

</form>
{% endblock %}

django/web/templates/web/timeline.html
{% extends 'base.html' %}
{% block title %}Timeline (last 24 hours){% endblock %}

{% block content %}
<div id="visualization" style="position: absolute; left: 0px; width: 100%;"></div>

<style>
  .vis-item.started {
  border-color: blue;
  }

  .vis-item.failed {
  border-color: red;
  }

  .vis-item.warning {
  border-color: #f90;
  }

  .vis-item.log {
  border-color: #ddd;
  }

  .vis-item.finished {
  border-color: #090;
  }
</style>

<script>
  var groups = new vis.DataSet({{ groups_json|safe }});

  // create a dataset with items
  // note that months are zero-based in the JavaScript Date object, so month 3 is April
  var items = new vis.DataSet({{ events_json|safe }});

  // create visualization
  var container = document.getElementById('visualization');
  var options = {
    // option groupOrder can be a property name or a sort function
    // the sort function must compare two groups and return a value
    //     > 0 when a > b
    //     < 0 when a < b
    //       0 when a == b
    groupOrder: function (a, b) {
      return a.value - b.value;
    },
			timeAxis: {
			scale: 'hour',
			step: 1
			},
			end: new Date(),
			start: new Date((new Date()).getTime() - 24*60*60000),
			stack: false,
  };

  var timeline = new vis.Timeline(container);
  timeline.setOptions(options);
  timeline.setGroups(groups);
  timeline.setItems(items);

</script>


{% endblock %}